### ISSUE TITLE
Libaio Library

### ISSUE THREAD

**Issue by FellRamos** [rehanvdm/lambda-oracle-instant-client-blog#2]
Hi, I was checking this project and it helped me a lot for what I needed.

But I wonder how can I download the libaio/libaio.so.1 file. Fortunately, in my project, there was already some libaio.so.1 file around (not sure from where), but now I wanted to document this but I just can't find how to have this file. 
I saw that the file can be installed directly in ubuntu, but I am on a mac, and I would prefer to download it manually, so I can document how to download it, and other people can add this file in their projects.

Thanks!

**Comment by rehanvdm** [comment]
Happy it helped.. It is kind of buried in the docs, if you look here https://oracle.github.io/node-oracledb/INSTALL.html#quickstart you will eventually read and find this link https://www.oracle.com/database/technologies/instant-client.html. There is a big download button, which takes you here https://www.oracle.com/database/technologies/instant-client/downloads.html look for the "Basic Light Package (ZIP) " download
